apiVersion: apps/v1
kind: Deployment
metadata:
  name: conexao-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: conexao-api

  template:
    metadata:
      labels:
        app: conexao-api

    spec:
      containers:
      - name: conexao-api
        image: conexao-api:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 8080