apiVersion: apps/v1
kind: Deployment
metadata:
  name: conexao-worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: conexao-worker

  template:
    metadata:
      labels:
        app: conexao-worker

    spec:
      containers:
      - name: conexao-worker
        image: conexao-worker:latest
        imagePullPolicy: Never