name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Docker Build API
      run: |
        docker build \
        -t conexao-solidaria-api \
        -f services/ConexaoSolidaria.Api/Dockerfile .

    - name: Docker Build Worker
      run: |
        docker build \
        -t conexao-solidaria-worker \
        -f services/ConexaoSolidaria.Worker/Dockerfile .